### ISSUE TITLE
Password Change

### ISSUE THREAD

**Issue by DarkMortal** [DarkMortal/Spaceapps-2021#6]
Not to point out the obvious, but if we don't add email support (like gmail or any other email providers), then users won't be able to change their password in case they forget

**Comment by dev-abir** [comment]
We need to build a prototype. In a real-life project, this feature is a necessity.

I think we should focus more on the required features, described in the challenge page, like: live view of editing of logs, tagging system, database and it's schema etc. These are probably more challenging ones and could take a lot of time building, debugging and testing them.
